9.1 tests
thinknetica-django-lab-01/jakosoll pull request #75
Opened 2021-02-18 14:30 UTC by jakosoll

Closes #73

2021-02-19 06:09 UTC, mikhailborodin requested changes

2021-02-19 06:09 UTC, mikhailborodin commented on django_lab/main/models.py
> +    _vendor = models.BooleanField('Является ли продавцом', default=False)
все поля в модели должны быть публичными

2021-02-19 06:09 UTC, mikhailborodin commented on django_lab/main/tests/test_pytests.py
> +def test_add_view_status_code(client, user):
данный тест не проверяет функционал создания товара, он проверяет ответ сервера при GET запросе по данному урлу

2021-02-19 06:09 UTC, mikhailborodin commented on django_lab/main/tests/test_pytests.py
> +def test_edit_view_status_code(client, product, user):
здесь то же самое, в тесте надо изменить товар и проверить изменился ли он

2021-02-19 07:28 UTC, jakosoll commented on django_lab/main/models.py
> +    _vendor = models.BooleanField('Является ли продавцом', default=False)
Исправлю, есть ли на это какие-то причины, о которых стоит знать?

2021-02-21 08:46 UTC, mikhailborodin approved these changes

2021-02-21 08:46 UTC, mikhailborodin commented on django_lab/main/tests/test_pytests.py
> +    assert b'test_name' in response.content
здесь же надо проверить 201 статус ответа сервера

2021-02-21 08:59 UTC, merged