9.5 channels
thinknetica-django-lab-01/jakosoll pull request #87
Opened 2021-02-22 22:25 UTC by jakosoll

Closes #74

2021-02-23 10:07 UTC, mikhailborodin requested changes

2021-02-23 10:07 UTC, mikhailborodin commented on django_lab/chat/consumers.py
> +    def disconnect(self, close_code):
если вы не хотите перегружать операторы родительских классов, то не надо делать пустой метод в дочернем классе

2021-02-23 10:43 UTC, jakosoll commented on django_lab/chat/consumers.py
> +    def disconnect(self, close_code):
Спасибо за замечание)

2021-02-24 09:49 UTC, mikhailborodin approved these changes

2021-02-24 10:56 UTC, merged