Set up docker-compose, postgress, redis, celery
thinknetica-django-lab-01/jakosoll pull request #91
Opened 2021-02-28 08:39 UTC by jakosoll

Closes #82

2021-02-28 09:24 UTC, mikhailborodin requested changes

2021-02-28 09:24 UTC, mikhailborodin commented on django_lab/docker-compose.yml
> +    command: python manage.py runserver 0.0.0.0:8000
используя докер мы уже готовим наш сервис в прод, а в проде приложение запускается через gunicorn  или uwsgi, не используйте runserver

2021-02-28 10:25 UTC, jakosoll commented on django_lab/docker-compose.yml
> +    command: python manage.py runserver 0.0.0.0:8000
Хорошо. Но для будущих студентов будет лучше, если уточните в задачке, что нужно подготовить сервис и для прода в том числе. Так будет яснее

2021-03-03 04:39 UTC, mikhailborodin approved these changes

2021-03-03 04:39 UTC, mikhailborodin commented on django_lab/django_lab/settings.py
> +        'LOCATION': 'redis://redis:6379/1',
этот урл тоже надо вынести в окружение, иначе без докера проект не запустится

2021-03-03 07:05 UTC, merged